### ISSUE TITLE
Not compatible with Gradle 7.0

### ISSUE THREAD

**Issue by ZakTaccardi** [jaredsburrows/gradle-spoon-plugin#97]
Make compatible with Gradle 7.0

Seeing:

```
FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task 'lib:spoonDebugAndroidTest' (type 'SpoonTask').
  - Type 'com.jaredsburrows.spoon.SpoonTask' property 'applicationApk' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.
```

As `applicationApk` is already marked with `@Internal` - maybe it needs to be marked with `@get:Internal` due to it being a `lateinit`?

https://github.com/jaredsburrows/gradle-spoon-plugin/blob/b9f5afa843e740d5737c3964018d780aad73d54f/src/main/kotlin/com/jaredsburrows/spoon/SpoonTask.kt#L20-L26

**Comment by ZakTaccardi** [comment]
Note - I'm using `1.5.1`

**Comment by ZakTaccardi** [comment]
note: I solved this _internally_ by forking the code in `master` and adding it into our `buildSrc`.

https://github.com/jaredsburrows/gradle-spoon-plugin/commit/b9f5afa843e740d5737c3964018d780aad73d54f

This is strange because it should be near identical to `1.5.1`. I didn't need to make any code changes. I think this is one of those things where there is a slight difference between building from source and from the artifact in `mavenCentral()`. I'd still guess that `@get:Internal` could be the fix, though I didn't need to add it when building from source

**Comment by jaredsburrows** [comment]
Should we add it back?

**Comment by ZakTaccardi** [comment]
The larger issue is that marking these inputs as `@Internal` is incorrect.

https://github.com/jaredsburrows/gradle-spoon-plugin/issues/98
https://github.com/jaredsburrows/gradle-spoon-plugin/pull/92#issuecomment-854944737

They affect whether the `SpoonTask` should execute or not.

**Comment by ZakTaccardi** [comment]
> Should we add it back?

If you are referring to https://github.com/jaredsburrows/gradle-spoon-plugin/pull/92 - then I would argue yes

**Comment by pavanagarwal** [comment]
We are seeing same issue on our project when we tried upgrading Android Gradle plugin to 7.0. Any updates or plans on fixing this?

**Comment by jaredsburrows** [comment]
Yes. Just hoping update with the Jcenter updates as well.

**Comment by mattinger** [comment]
There's also issues on top of this due to the use of ddmlib which has changed certainly with build tools 30.

```
Caused by: java.lang.NoSuchMethodError: com.android.ddmlib.logcat.LogCatMessage.getTimestamp()Lcom/android/ddmlib/logcat/LogCatTimestamp;
        at com.squareup.spoon.html.HtmlLog$LogEntry.from(HtmlLog.java:68)
        at com.squareup.spoon.html.HtmlLog.from(HtmlLog.java:36)
        at com.squareup.spoon.html.HtmlRenderer.generateLogHtml(HtmlRenderer.java:145)
        at com.squareup.spoon.html.HtmlRenderer.render(HtmlRenderer.java:63)
```

This is an issue with spoon itself, which it seems isn't getting very much in the way of updates.  They haven't put out a release in a long time, and has seen 2 commits in 3 years.

**Comment by mattinger** [comment]
@jaredsburrows Are there any planned workarounds to spoon itself and ddmlib issues i mentioned?  I'm not sure what could even be done, but i'm curious about your thoughts on it.

**Comment by ZakTaccardi** [comment]
@mattinger did you find any workarounds to the `NoSuchMethodError` or is it time to abandon Spoon?

note: created relevant Spoon issue here https://github.com/square/spoon/issues/583

**Comment by mattinger** [comment]
@ZakTaccardi We abandoned spoon and migrated to Marathon

**Comment by rajvinodh** [comment]
After updating the plugin to 1.5.1 version. I had same issue. Even though adding **clean** with **gradle** command worked for me, it was time taking.

Instead deleting spoon-output folder before running gradle command solved my problem. 

Note - spoon-output is present in build folder. Also spoon-output is not the custom directory that we give in spoon.gradle. 

This folder is created by spoon plugin itself, need to debug the reason for this.

**Comment by jaredsburrows** [comment]
I believe this has bene fixed(https://github.com/jaredsburrows/gradle-spoon-plugin/blob/c6036263197165948348d7f78b77698c3f0b28ae/src/main/kotlin/com/jaredsburrows/spoon/SpoonTask.kt) and the fixed version is ok `mavenCentral()`.
